language: c
dist: bionic

jobs:
  include:
  - compiler: clang
    os: linux
    addons:
      apt:
        packages:
        - libglade2-dev
        - libgnomeui-dev
        - libgtk2.0-dev
        - scrollkeeper
        - gnome-doc-utils
        - gtk-doc-tools
  - compiler: gcc
    os: linux
    addons:
      apt:
        packages:
        - libglade2-dev
        - libgnomeui-dev
        - libgtk2.0-dev
        - scrollkeeper
        - gnome-doc-utils
        - gtk-doc-tools

before_script:
  - autoreconf -i -f -Wno-portability

script:
  - ./configure --disable-silent-rules
  - cat config.log
  - make
