language: c
dist: bionic

jobs:
  include:
  - compiler: clang
    os: linux
    addons:
      apt:
        packages:
        - libglade2-dev
        - libgnomeui-dev
        - libgtk2.0-dev
        - scrollkeeper
        - gnome-doc-utils
  - compiler: gcc
    os: linux
    addons:
      apt:
        packages:
        - libglade2-dev
        - libgnomeui-dev
        - libgtk2.0-dev
        - scrollkeeper
        - gnome-doc-utils

before_script:
  - autoreconf -i -f -Wno-portability
  - git clone -b dev https://github.com/mdbtools/mdbtools.git mdbtools
  - cd mdbtools && autoreconf -i -f && ./configure && make && sudo make install && cd ..

script:
  - ./configure --disable-silent-rules
  - make
